#* @project_name : Masky-Md
#   * @author : Masky bot info 
#   * @youtube : https://www.youtube.com/@Maskybot01
#   * @description : Masky-Md ,A Multi-functional whatsapp user bot.
#   * @version 2.5.0
#*
#* 
#   * Created By Masky Tech Info.
#   * © 2024 Masky-Md.

# Don't change this [ /GiftedTech/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/Masky01bot/Masky_Bot
RUN git clone https://github.com/Masky01bot/Masky_Bot /root/MaskyMd
WORKDIR /root/Masky_Bot/
RUN npm install
EXPOSE 8000
CMD ["node","lib/smd.js" ] 
